Repository aws/aws-parallelcluster-node, pull requests merged in 2022-05, with the labels that each got.

#405 Add additional tests for node healthiness
  tests/slurm_plugin/slurm_resources/test_slurm_resources.py
Labels: skip-changelog-update

#406 Set unhealthy nodes static nodes to down with reset node address
  src/slurm_plugin/clustermgtd.py
  tests/slurm_plugin/test_clustermgtd.py
Labels: skip-changelog-update, 3.x

#409 Bump node to version 2.11.7
  setup.py
Labels: skip-changelog-update

#408 Bump version to 3.1.4
  setup.py
Labels: skip-changelog-update, 3.x

#411 Update changelog of 3.1.4
  CHANGELOG.md
Labels: 3.x

#414 Add Unsupported state in the list of EC2 error codes used for fast fail-over
  src/slurm_plugin/slurm_resources.py
  tests/slurm_plugin/slurm_resources/test_slurm_resources.py
Labels: skip-changelog-update, 3.x
