Repository aws/aws-parallelcluster-node, pull requests merged in 2022-12, with the labels that each got.

#470 [tox] Replace whitelist_externals with allowlist_externals in tox.ini
  tox.ini
Labels: skip-changelog-update

#468 [Versioning] Bump version to 3.4.0
  setup.py
Labels: skip-changelog-update

#472 Revert "Implement workaround for dynamic nodes stuck in bad Slurm state"
  CHANGELOG.md
  src/slurm_plugin/slurm_resources.py
  tests/slurm_plugin/slurm_resources/test_slurm_resources.py
Labels: 3.x

#473 Wip/release 3.4/slurm 22.05.6 upgrade
  CHANGELOG.md
  src/slurm_plugin/slurm_resources.py
  tests/slurm_plugin/slurm_resources/test_slurm_resources.py
Labels: 3.x

#478 [develop] Removed skip rule for finding B105 from the bandit conf
  .bandit.ini
Labels: skip-changelog-update, 3.x
