Repository aws/aws-parallelcluster-node, pull requests merged in 2022-11, with the labels that each got.

#454 Bump to version 3.1.5
  setup.py
Labels: skip-changelog-update

#456 Support compute node launches on multiple subnets across availability zones
  CHANGELOG.md
  src/slurm_plugin/fleet_manager.py
  tests/common.py
  tests/slurm_plugin/test_fleet_manager.py
  tests/slurm_plugin/test_fleet_manager/TestCreateFleetManager/test_evaluate_launch_params/all_or_nothing/expected_launch_params.json
  tests/slurm_plugin/test_fleet_manager/TestCreateFleetManager/test_evaluate_launch_params/fleet-multi-az-multi-it/expected_launch_params.json
  tests/slurm_plugin/test_fleet_manager/TestCreateFleetManager/test_evaluate_launch_params/fleet-multi-az-single-it-all_or_nothing/expected_launch_params.json
  tests/slurm_plugin/test_fleet_manager/TestCreateFleetManager/test_evaluate_launch_params/fleet-single-az-multi-it-all_or_nothing/expected_launch_params.json
  tests/slurm_plugin/test_fleet_manager/TestCreateFleetManager/test_evaluate_launch_params/fleet_ondemand/expected_launch_params.json
  tests/slurm_plugin/test_fleet_manager/TestCreateFleetManager/test_evaluate_launch_params/fleet_spot/expected_launch_params.json
  tests/slurm_plugin/test_fleet_manager/TestCreateFleetManager/test_evaluate_launch_params/launch_overrides/expected_launch_params.json
Labels: enhancement, 3.x

#458 [3.x] Update CODEOWNERS
  .github/CODEOWNERS
Labels: skip-changelog-update

#460 [Versioning] Bump version to 3.4.0b1
  setup.py
Labels: skip-changelog-update, 3.x

#437 3.x Update 'black' version in pre-commit hook to v22.6.0
  .isort.cfg
  .pre-commit-config.yaml
Labels: skip-changelog-update, 3.x

#466 [develop] Fix flake8 config
  .flake8
Labels: skip-changelog-update

#462 [MultiAZ] Log a warning when using multiple AZs and InstanceTypes while all-or-nothing is enabled.
  src/slurm_plugin/fleet_manager.py
  tests/slurm_plugin/test_fleet_manager.py
  tests/slurm_plugin/test_fleet_manager/TestCreateFleetManager/test_evaluate_launch_params/fleet-multi-az-multi-it-all_or_nothing/expected_launch_params.json
Labels: skip-changelog-update, 3.x
