Repository aws/aws-parallelcluster-node, pull requests merged in 2023-06, with the labels that each got.

#528 Fix FleetManager behavior when create-fleet returns no instances
  CHANGELOG.md
  src/slurm_plugin/instance_manager.py
  tests/slurm_plugin/test_fleet_manager.py
  tests/slurm_plugin/test_instance_manager.py
Labels: 3.x

#537 [3.6] Avoid duplication of nodes in `ClusterManager._find_active_nodes()`
  CHANGELOG.md
  src/slurm_plugin/clustermgtd.py
  tests/slurm_plugin/test_clustermgtd.py
Labels: 3.x

#538 [develop] Avoid duplication of nodes in `ClusterManager._find_active_nodes()`
  CHANGELOG.md
  src/slurm_plugin/clustermgtd.py
  tests/slurm_plugin/test_clustermgtd.py
Labels: 3.x

#529 3.x Add a event publisher to push protected mode error log to cloud watch
  src/slurm_plugin/cluster_event_publisher.py
  src/slurm_plugin/clustermgtd.py
  tests/slurm_plugin/test_cluster_event_publisher.py
Labels: skip-changelog-update, 3.x

#530 Push instance-to-node mapping from clustermgtd to log file
  src/slurm_plugin/cluster_event_publisher.py
  src/slurm_plugin/clustermgtd.py
  src/slurm_plugin/fleet_manager.py
  src/slurm_plugin/instance_manager.py
  src/slurm_plugin/logging/parallelcluster_clustermgtd_logging.conf
  tests/slurm_plugin/test_cluster_event_publisher.py
  tests/slurm_plugin/test_instance_manager.py
  tests/slurm_plugin/test_resume.py
Labels: skip-changelog-update

#536 Run jobinfomgtd to collect job information to a local file
  setup.py
  src/common/schedulers/slurm_commands.py
  src/slurm_plugin/cluster_event_publisher.py
  src/slurm_plugin/clusterjobinfomgtd.py
  src/slurm_plugin/logging/jobinfomgtd_logging.conf
  src/slurm_plugin/slurm_resources.py
Labels: skip-changelog-update, skip-security-exclusions-check
