Repository aws/aws-parallelcluster-node, pull requests merged in 2023-04, with the labels that each got.

#511 3.x Add metric for longest dynamic node idle time
  src/common/schedulers/slurm_commands.py
  src/slurm_plugin/cluster_event_publisher.py
  src/slurm_plugin/clustermgtd.py
  src/slurm_plugin/logging/parallelcluster_clustermgtd_logging.conf
  src/slurm_plugin/slurm_resources.py
  tests/common/schedulers/test_slurm_commands.py
  tests/slurm_plugin/test_cluster_event_publisher.py
Labels: skip-changelog-update, 3.x

#514 [develop]Remove duplicated log info
  src/slurm_plugin/fleet_status_manager.py
  src/slurm_plugin/resume.py
Labels: skip-changelog-update

#515 Bump version to 3.7.0
  CHANGELOG.md
  setup.py
Labels: skip-changelog-update

#516 Bump version to 3.6.0b1
  setup.py
Labels: skip-changelog-update

#517 3.x Lower log level of instance state events
  src/slurm_plugin/cluster_event_publisher.py
  tests/slurm_plugin/test_cluster_event_publisher.py
Labels: skip-changelog-update, 3.x

#519 [3.x] Update attribution doc
  THIRD-PARTY-LICENSES.txt
Labels: skip-changelog-update

#518 [3.6] Update attribution doc
  THIRD-PARTY-LICENSES.txt
Labels: skip-changelog-update

#522 3.6 Lower log level of instance state events
  src/slurm_plugin/cluster_event_publisher.py
  tests/slurm_plugin/test_cluster_event_publisher.py
Labels: skip-changelog-update, 3.x

#523 3.x Fix publish event exception at debug level
  src/slurm_plugin/cluster_event_publisher.py
  tests/slurm_plugin/test_cluster_event_publisher.py
Labels: bug, skip-changelog-update, 3.x
