Repository aws/aws-parallelcluster-node, pull requests merged in 2023-10, with the labels that each got.

#566 Support specification of multiple scaling strategies
  src/slurm_plugin/common.py
  src/slurm_plugin/instance_manager.py
  src/slurm_plugin/resume.py
  tests/slurm_plugin/test_common.py
  tests/slurm_plugin/test_instance_manager.py
  tests/slurm_plugin/test_resume.py
Labels: skip-changelog-update, 3.x

#568 Skip job-level launch when using BEST_EFFORT scaling strategy.
  src/slurm_plugin/instance_manager.py
  tests/slurm_plugin/test_instance_manager.py
Labels: skip-changelog-update, 3.x

#569 Add support for greedy-all-or-nothing
  src/slurm_plugin/common.py
  src/slurm_plugin/instance_manager.py
  tests/slurm_plugin/test_instance_manager.py
Labels: skip-changelog-update, 3.x

#571 Disable deprecated flake8-mypy Python tox check
  .pre-commit-config.yaml
  tox.ini
Labels: skip-changelog-update, 3.x

#572 Disable deprecated flake8-mypy Python tox check
  .pre-commit-config.yaml
  tox.ini
Labels: skip-changelog-update, 3.x

#573 [develop] Avoid scaling if content of SLURM_RESUME_FILE is empty
  src/slurm_plugin/instance_manager.py
  tests/slurm_plugin/test_instance_manager.py
  tests/slurm_plugin/test_resume.py
Labels: skip-changelog-update

#574 [develop] Remove separation between oversubscribe and no-oversubscribe jobs
  src/slurm_plugin/instance_manager.py
  src/slurm_plugin/slurm_resources.py
  tests/slurm_plugin/test_instance_manager.py
Labels: skip-changelog-update

#575 Add 3.7.2 entry in the changelog
  CHANGELOG.md
Labels: 3.x

#576 Permit test_slurm_commands to pass on MacOS
  tests/common/schedulers/test_slurm_commands.py
Labels: skip-changelog-update

#580 Bump version to 3.9.0
  setup.py
Labels: skip-changelog-update, 3.x

#581 Bump version to 3.8.0b1
  setup.py
Labels: skip-changelog-update, 3.x

#584 [release-3.8] Log the process ID of the currently running Slurm Resume Program
  src/slurm_plugin/logging/parallelcluster_resume_logging.conf
  src/slurm_plugin/resume.py
Labels: skip-changelog-update

#585 [develop] Log when no instances are available for nodes assignment
  src/slurm_plugin/instance_manager.py
Labels: skip-changelog-update

#586 [release-3.8] Log when no instances are available for nodes assignment
  src/slurm_plugin/instance_manager.py
Labels: skip-changelog-update

#588 Rebuild attribution document
  THIRD-PARTY-LICENSES.txt
Labels: skip-changelog-update, 3.x, skip-security-exclusions-check

#589 [release-3.8] Avoid scale-all optimization for all-or-nothing when single job
  src/slurm_plugin/instance_manager.py
  tests/slurm_plugin/test_instance_manager.py
Labels: skip-changelog-update

#590 [develop] Avoid scale-all optimization for all-or-nothing when single job
  src/slurm_plugin/instance_manager.py
  tests/slurm_plugin/test_instance_manager.py
Labels: skip-changelog-update
