Repository aws/aws-parallelcluster-node, pull requests merged in 2024-02, with the labels that each got.

#612 Update the attribution document for 3.9.0
  THIRD-PARTY-LICENSES.txt
Labels: skip-changelog-update, 3.x

#614 [develop] Improve Clustermgtd logic to consider all IP(s) on an instance
  src/common/ec2_utils.py
  src/slurm_plugin/clustermgtd.py
  src/slurm_plugin/fleet_manager.py
  src/slurm_plugin/instance_manager.py
  tests/common/test_ec2_utils.py
  tests/slurm_plugin/slurm_resources/test_slurm_resources.py
  tests/slurm_plugin/test_cluster_event_publisher.py
  tests/slurm_plugin/test_clustermgtd.py
  tests/slurm_plugin/test_instance_manager.py
  tests/slurm_plugin/test_resume.py
Labels: skip-changelog-update

#615 [DEX] Add possibility in 'upload-node.sh' to specify an optional scope
  util/upload-node.sh
Labels: skip-changelog-update, 3.x, Developer Experience

#616 Remove unnecessary nested if in is_backing_instance_valid()
  src/slurm_plugin/slurm_resources.py
Labels: skip-changelog-update

#617 Set `ec2_instance_missing_max_count` default to 0, to match behavior before the option was added.
  src/slurm_plugin/clustermgtd.py
Labels: skip-changelog-update

#618 [Release] Add logic to is_backing_instance_valid to check the IP to make sure t…
  src/slurm_plugin/clustermgtd.py
  src/slurm_plugin/slurm_resources.py
  tests/slurm_plugin/slurm_resources/test_slurm_resources.py
  tests/slurm_plugin/test_clustermgtd.py
Labels: skip-changelog-update
