Repository aws/aws-parallelcluster-node, pull requests merged in 2024-07, with the labels that each got.

#634 Add Github Manual workflow to bump version
  .github/workflows/bump_version.yml
Labels: skip-changelog-update

#637 [Docs] Add changelog for version 3.10.1.
  CHANGELOG.md
Labels: 3.x, Versioning

#638 Add permissions to Github workflows to bump version
  .github/workflows/bump_version.yml
Labels: skip-changelog-update

#639 [Bugfix] Fix a bug that was causing `clustermgtd` to fail when a field returned by the command `scontrol show nodes` has a value that contains the character `=`.
  CHANGELOG.md
  src/common/schedulers/slurm_commands.py
  tests/common/schedulers/test_slurm_commands.py
Labels: bug, 3.x
